/**
 * @module knowledge/built-in-patterns
 * 6 built-in failure patterns seeded during migration v2.
 * Exported for use in tests and validation.
 */

import type { FailurePattern } from './types.js';

export const BUILT_IN_PATTERNS: FailurePattern[] = [
  {
    id: 'builtin-conn-refused',
    category: 'CONNECTION_REFUSED',
    signature: 'builtin::CONNECTION_REFUSED',
    signaturePattern: 'ECONNREFUSED *:*',
    description: 'Service connection refused',
    suggestedFix: '服务可能未完全启动，尝试增加 healthcheck.startPeriod',
    confidence: 0.5,
    occurrences: 0,
    resolutions: 0,
    source: 'built-in',
    firstSeenAt: '',
    lastSeenAt: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'builtin-timeout',
    category: 'TIMEOUT',
    signature: 'builtin::TIMEOUT',
    signaturePattern: 'ETIMEDOUT / timeout exceeded',
    description: 'Request or operation timed out',
    suggestedFix: '请求超时，检查服务响应时间或增加 timeout 配置',
    confidence: 0.5,
    occurrences: 0,
    resolutions: 0,
    source: 'built-in',
    firstSeenAt: '',
    lastSeenAt: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'builtin-container-oom',
    category: 'CONTAINER_OOM',
    signature: 'builtin::CONTAINER_OOM',
    signaturePattern: 'OOMKilled = true',
    description: 'Container killed due to out of memory',
    suggestedFix: '容器内存不足，增加 container memory limit 或优化内存使用',
    confidence: 0.5,
    occurrences: 0,
    resolutions: 0,
    source: 'built-in',
    firstSeenAt: '',
    lastSeenAt: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'builtin-http-error',
    category: 'HTTP_ERROR',
    signature: 'builtin::HTTP_ERROR',
    signaturePattern: 'returned 5xx',
    description: 'HTTP server error response',
    suggestedFix: '服务端错误，检查容器日志定位 root cause',
    confidence: 0.5,
    occurrences: 0,
    resolutions: 0,
    source: 'built-in',
    firstSeenAt: '',
    lastSeenAt: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'builtin-mock-mismatch',
    category: 'MOCK_MISMATCH',
    signature: 'builtin::MOCK_MISMATCH',
    signaturePattern: 'mock unexpected request',
    description: 'Mock service received unexpected request',
    suggestedFix: 'Mock 服务收到未预期请求，检查 mock routes 配置是否完整',
    confidence: 0.5,
    occurrences: 0,
    resolutions: 0,
    source: 'built-in',
    firstSeenAt: '',
    lastSeenAt: '',
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'builtin-assertion',
    category: 'ASSERTION_MISMATCH',
    signature: 'builtin::ASSERTION_MISMATCH',
    signaturePattern: 'expected .* to (equal|match|be)',
    description: 'Test assertion failed',
    suggestedFix: '断言失败，检查测试期望值或服务返回值是否正确',
    confidence: 0.5,
    occurrences: 0,
    resolutions: 0,
    source: 'built-in',
    firstSeenAt: '',
    lastSeenAt: '',
    createdAt: '',
    updatedAt: '',
  },
];
